import 'package:flutter/material.dart';
import '../core/app_colors.dart';
import '../core/user_session.dart';
import 'treasury_details_screen.dart';

/// Gate screen shown to any member who tries to access the treasury.
/// They must enter the 6-character code generated by the pastor/treasurer.
/// On success, a timed [TreasuryAccessSession] is created and the
/// treasury opens with a live countdown banner.
class TreasuryLockScreen extends StatefulWidget {
  const TreasuryLockScreen({super.key});

  @override
  State<TreasuryLockScreen> createState() => _TreasuryLockScreenState();
}

class _TreasuryLockScreenState extends State<TreasuryLockScreen>
    with SingleTickerProviderStateMixin {
  final _codeCtrl = TextEditingController();
  bool _error = false;
  String _errorMsg = '';

  // Pulse animation for the lock icon
  late final AnimationController _pulseCtrl;
  late final Animation<double> _pulseAnim;

  @override
  void initState() {
    super.initState();
    _pulseCtrl = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 2),
    )..repeat(reverse: true);
    _pulseAnim = Tween<double>(begin: 0.94, end: 1.0).animate(
      CurvedAnimation(parent: _pulseCtrl, curve: Curves.easeInOut),
    );

    // If there's already a valid active session, skip straight to treasury
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final session = treasuryAccessNotifier.value;
      if (session != null && !session.isExpired) {
        _openTreasury();
      }
    });
  }

  @override
  void dispose() {
    _pulseCtrl.dispose();
    _codeCtrl.dispose();
    super.dispose();
  }

  void _tryUnlock() {
    final entered = _codeCtrl.text.trim().toUpperCase();
    if (entered.isEmpty) {
      setState(() {
        _error = true;
        _errorMsg = 'Please enter the access code.';
      });
      return;
    }

    final activeCode = treasuryUnlockCodeNotifier.value;

    if (activeCode == null) {
      setState(() {
        _error = true;
        _errorMsg = 'No active code has been generated. '
            'Ask your pastor or treasurer to generate one.';
      });
      return;
    }

    if (activeCode.isExpired) {
      setState(() {
        _error = true;
        _errorMsg = 'This code has expired. '
            'Ask your pastor or treasurer for a new one.';
      });
      // Clear the expired code
      treasuryUnlockCodeNotifier.value = null;
      return;
    }

    if (entered != activeCode.code) {
      setState(() {
        _error = true;
        _errorMsg = 'Incorrect code. Please try again.';
      });
      return;
    }

    // ✅ Valid — grant access
    final session = TreasuryAccessSession(expiresAt: activeCode.expiresAt);
    treasuryAccessNotifier.value = session;
    _openTreasury();
  }

  void _openTreasury() {
    Navigator.pushReplacement(
      context,
      MaterialPageRoute(builder: (_) => const TreasuryDetailsScreen()),
    );
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final bg = isDark ? AppColors.backgroundDark : AppColors.backgroundLight;
    final textColor = isDark ? Colors.white : Colors.black87;
    final subColor =
        isDark ? const Color(0xFF94A3B8) : const Color(0xFF475569);
    final cardBg = isDark ? const Color(0xFF1E293B) : Colors.white;
    final borderColor =
        isDark ? const Color(0xFF334155) : const Color(0xFFE2E8F0);

    return Scaffold(
      backgroundColor: bg,
      body: SafeArea(
        bottom: false,
        child: Column(
          children: [
            // Header
            Padding(
              padding: const EdgeInsets.fromLTRB(4, 4, 16, 4),
              child: Row(
                children: [
                  IconButton(
                    icon: Icon(Icons.arrow_back, color: textColor),
                    onPressed: () => Navigator.maybePop(context),
                  ),
                  Expanded(
                    child: Text(
                      'Church Treasury',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                        letterSpacing: -0.3,
                        color: textColor,
                      ),
                    ),
                  ),
                  const SizedBox(width: 48),
                ],
              ),
            ),

            Expanded(
              child: SingleChildScrollView(
                padding: EdgeInsets.fromLTRB(
                    28, 24, 28, MediaQuery.of(context).padding.bottom + 32),
                child: Column(
                  children: [
                    // Animated lock illustration
                    ScaleTransition(
                      scale: _pulseAnim,
                      child: Stack(
                        alignment: Alignment.center,
                        children: [
                          Container(
                            width: 130,
                            height: 130,
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              color: const Color(0xFFEF4444).withOpacity(0.08),
                            ),
                          ),
                          Container(
                            width: 100,
                            height: 100,
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              color: const Color(0xFFEF4444).withOpacity(0.12),
                            ),
                          ),
                          const Icon(
                            Icons.lock_rounded,
                            color: Color(0xFFEF4444),
                            size: 52,
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(height: 28),

                    Text(
                      'Treasury is Locked',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 26,
                        fontWeight: FontWeight.bold,
                        letterSpacing: -0.5,
                        color: textColor,
                      ),
                    ),
                    const SizedBox(height: 12),
                    Text(
                      'Access to the church treasury is restricted '
                      'to protect financial information. '
                      'Ask your pastor or treasurer to generate '
                      'a temporary access code.',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 14,
                        height: 1.7,
                        color: subColor,
                      ),
                    ),
                    const SizedBox(height: 36),

                    // Info chips row
                    Row(
                      children: [
                        _InfoChip(
                          icon: Icons.timer_outlined,
                          label: '10–15 min only',
                          isDark: isDark,
                        ),
                        const SizedBox(width: 10),
                        _InfoChip(
                          icon: Icons.admin_panel_settings_outlined,
                          label: 'Pastor approved',
                          isDark: isDark,
                        ),
                        const SizedBox(width: 10),
                        _InfoChip(
                          icon: Icons.lock_reset,
                          label: 'Auto-locks',
                          isDark: isDark,
                        ),
                      ],
                    ),
                    const SizedBox(height: 32),

                    // Code input
                    Container(
                      padding: const EdgeInsets.all(20),
                      decoration: BoxDecoration(
                        color: cardBg,
                        borderRadius: BorderRadius.circular(16),
                        border: Border.all(
                          color: _error
                              ? const Color(0xFFEF4444)
                              : borderColor,
                          width: _error ? 1.5 : 1,
                        ),
                        boxShadow: [
                          BoxShadow(
                            color: Colors.black.withOpacity(0.04),
                            blurRadius: 10,
                            offset: const Offset(0, 3),
                          ),
                        ],
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            'ENTER ACCESS CODE',
                            style: TextStyle(
                              fontSize: 10,
                              fontWeight: FontWeight.w700,
                              letterSpacing: 1.5,
                              color: subColor,
                            ),
                          ),
                          const SizedBox(height: 10),
                          TextField(
                            controller: _codeCtrl,
                            textCapitalization:
                                TextCapitalization.characters,
                            maxLength: 6,
                            style: TextStyle(
                              fontSize: 22,
                              fontWeight: FontWeight.bold,
                              letterSpacing: 6,
                              color: textColor,
                            ),
                            decoration: InputDecoration(
                              hintText: '• • • • • •',
                              hintStyle: TextStyle(
                                fontSize: 18,
                                letterSpacing: 4,
                                color: subColor.withOpacity(0.4),
                              ),
                              counterText: '',
                              border: InputBorder.none,
                              enabledBorder: InputBorder.none,
                              focusedBorder: InputBorder.none,
                            ),
                            onChanged: (_) {
                              if (_error) setState(() => _error = false);
                            },
                            onSubmitted: (_) => _tryUnlock(),
                          ),
                          if (_error) ...[
                            const SizedBox(height: 8),
                            Row(
                              children: [
                                const Icon(Icons.error_outline,
                                    color: Color(0xFFEF4444), size: 14),
                                const SizedBox(width: 6),
                                Expanded(
                                  child: Text(
                                    _errorMsg,
                                    style: const TextStyle(
                                      fontSize: 12,
                                      color: Color(0xFFEF4444),
                                      height: 1.4,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ],
                        ],
                      ),
                    ),
                    const SizedBox(height: 20),

                    // Unlock button
                    SizedBox(
                      width: double.infinity,
                      height: 52,
                      child: ElevatedButton.icon(
                        onPressed: _tryUnlock,
                        icon: const Icon(Icons.lock_open_rounded, size: 20),
                        label: const Text(
                          'Unlock Treasury',
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: AppColors.primary,
                          foregroundColor: Colors.white,
                          elevation: 4,
                          shadowColor: AppColors.primary.withOpacity(0.3),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 28),

                    // Scripture
                    Text(
                      '"Bring the whole tithe into the storehouse… '
                      'and see if I will not throw open the floodgates '
                      'of heaven." — Malachi 3:10',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 12,
                        height: 1.65,
                        fontStyle: FontStyle.italic,
                        color: subColor.withOpacity(0.65),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _InfoChip extends StatelessWidget {
  final IconData icon;
  final String label;
  final bool isDark;

  const _InfoChip(
      {required this.icon, required this.label, required this.isDark});

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 8, horizontal: 6),
        decoration: BoxDecoration(
          color: isDark
              ? const Color(0xFF1E293B)
              : AppColors.primary.withOpacity(0.05),
          borderRadius: BorderRadius.circular(10),
          border: Border.all(
            color: AppColors.primary.withOpacity(0.15),
          ),
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(icon, color: AppColors.primary, size: 18),
            const SizedBox(height: 4),
            Text(
              label,
              textAlign: TextAlign.center,
              style: const TextStyle(
                fontSize: 10,
                fontWeight: FontWeight.w600,
                color: AppColors.primary,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
